version: '3.3'
services:

  frontend:
    image: gagai/foodgram-frontend:latest
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - backend_static_value:/var/html/backend_static/
      - backend_media_value:/var/html/backend_media/
    depends_on:
      - backend

  postgresql:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: gagai/foodgram-backend:latest
    restart: always
    expose:
      - 8000
    volumes:
      - backend_static_value:/app/backend_static/
      - backend_media_value:/app/backend_media/
    depends_on:
      - postgresql
    env_file:
      - ./.env

volumes:
  backend_static_value:
  backend_media_value:
