# Generated by Django 4.1.3 on 2022-11-30 17:51

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingridient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название ингридиента')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Количество в юнитах')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Назови своё блюдо!', max_length=100, verbose_name='Название рецепта')),
                ('text', models.TextField(help_text='Напиши рецепт блюда!', verbose_name='Текст рецепта')),
                ('cooking_time', models.PositiveSmallIntegerField(help_text='Сколько минут займёт готовка?', verbose_name='Время готовки в минутах')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название тега', max_length=30, verbose_name='Название тега')),
                ('color', colorfield.fields.ColorField(default='#2A6CAA', image_field=None, max_length=18, samples=None)),
                ('slug', models.SlugField()),
            ],
        ),
    ]
